### ISSUE TITLE
Question: what does inter-word do?

### ISSUE THREAD

**Issue by nestor-diaz** [12358-lab/my-portfolio#13]
https://github.com/12358-lab/my-portfolio/blob/dd538f57e6e420ff1010303713442f1722860cc4/src/pages/blog/blog.css#L3

**Comment by beatrizsanchezt** [comment]
There are a couple of ways to justify the text, like changing space between words or characters. This one Increases or decreases the space between words.

**Comment by beatrizsanchezt** [comment]
The default value is auto, "The browser determines the justification algorithm".
