### ISSUE TITLE
Figure out how to redirect domain without www

### ISSUE THREAD

**Issue by nestor-diaz** [12358-lab/my-portfolio#50]
Going directly with `http://beatrizsanchez.dev` does not work. There should be way to redirect the domain to the `www` version.

**Comment by beatrizsanchezt** [comment]
Fixed, GoDaddy -> Forwarding section.

**Comment by nestor-diaz** [comment]
it worked but the certificate isn't took:
![image](https://user-images.githubusercontent.com/25233189/74646920-a683d280-5172-11ea-861f-394b645c1b2a.png)

**Comment by nestor-diaz** [comment]
It worked but looks like the certificate isn't took.

**Comment by beatrizsanchezt** [comment]
Fixed.
